# Generated by Django 3.2.12 on 2024-04-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
            preserve_default=False,
        ),
    ]
