# Generated by Django 3.2.12 on 2024-04-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='des',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='src',
        ),
        migrations.AddField(
            model_name='reservation',
            name='destinaton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_seconday', to='api.station'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roat', to='api.station'),
        ),
        migrations.AddField(
            model_name='trains',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='trains',
            name='seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pnr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
