# Generated by Django 3.2.12 on 2024-04-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240407_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='tno',
            new_name='tname',
        ),
    ]
