# Generated by Django 3.2.12 on 2024-04-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240407_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='tname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
