# Generated by Django 3.2.12 on 2024-04-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_station_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='rid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.route'),
            preserve_default=False,
        ),
    ]
