# Generated by Django 3.2.12 on 2024-04-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_routestation_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='rid',
        ),
    ]
