# Generated by Django 3.2.12 on 2024-04-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_station_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='dstation',
        ),
        migrations.RemoveField(
            model_name='route',
            name='ostation',
        ),
        migrations.AddField(
            model_name='route',
            name='Dstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dstayon', to='api.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='Ostation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_p', to='api.station'),
        ),
    ]
